spring:
  profiles:
    active: local
    group:
      local: # When running local, common also runs
        - common
      prod:  # When running prod, common also runs
        - common
---
spring:
  profiles:
    active:
      on-profile: common
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---
spring:
  profiles:
    active:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kakaoapi
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
---
spring:
  profiles:
    active:
      on-profile: prod